### ISSUE TITLE
Installation failed with pip3

### ISSUE THREAD

**Issue by laleye** [bedapudi6788/deepsegment#1]
I got this error by installing via pip in an environment using python3

Using cached https://files.pythonhosted.org/packages/93/4b/979db9e44be09f71e85c9c8cfc42f258adfb7d93ce01deed2788b2948919/logging-0.4.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/logging.egg-info
    writing pip-egg-info/logging.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/logging.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/logging.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/logging.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sb7rjvuw/logging/setup.py", line 13, in <module>
        packages = ["logging"],
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.5/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.5/distutils/dist.py", line 846, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/dist.py", line 635, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/command/build_py.py", line 15, in <module>
        from setuptools.lib2to3_ex import Mixin2to3
      File "/home/frejus/.virtualenvs/labforsims_neonat/local/lib/python3.5/site-packages/setuptools/lib2to3_ex.py", line 12, in <module>
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package
      File "/usr/lib/python3.5/lib2to3/refactor.py", line 19, in <module>
        import logging
      File "/tmp/pip-install-sb7rjvuw/logging/logging/__init__.py", line 618
        raise NotImplementedError, 'emit must be implemented '\
                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-sb7rjvuw/logging/

**Comment by bedapudi6788** [comment]
Hi @laleye  this seems to be because pip is trying to install logging module, which should be present by default in Python 3 environments. Please take a look at https://stackoverflow.com/questions/32386469/logging-module-not-working-with-python3 and try uninstalling the logging module. Please let me know if this works.

**Comment by laleye** [comment]
Hi @bedapudi6788 
I tried the link solution but nothing. So, I cloned the repository and made the install from the setup and it worked.

**Comment by bedapudi6788** [comment]
@laleye thanks for the info, I will try to figure what happened when I get some time. I am also checking the compatibility with all Python versions and will update the setup.py for the same.
