### ISSUE TITLE
Facing error when running sample script

### ISSUE THREAD

**Issue by rvtechnogen** [bedapudi6788/deepsegment#16]
I was trying to set up the library to test the accuracy for my usecase.
I did the package installs and created a script containing just the content from the readme
When executing it i am facing the following error

Traceback (most recent call last):
  File "correct.py", line 4, in <module>
    print(segmenter.segment('I am Batman i live in gotham'))
  File "/home/algante/tmp/deepspeech-venv/lib/python3.6/site-packages/deepsegment/deepsegment.py", line 149, in segment
    all_tags = get_tf_serving_respone(DeepSegment.seqtag_model, encoded_sents)
  File "/home/algante/tmp/deepspeech-venv/lib/python3.6/site-packages/deepsegment/deepsegment.py", line 73, in get_tf_serving_respone
    response =stub.Predict(request, 20)
  File "/home/algante/tmp/deepspeech-venv/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/algante/tmp/deepspeech-venv/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1570094221.600498100","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1570094221.600481900","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"

Can someone help with this?

**Comment by bedapudi6788** [comment]
looks like you are using with tf-serving docker image. check if the image is running properly.

**Comment by bedapudi6788** [comment]
@rvtechnogen I am closing the issue. Feel free to re-open if it's not resolved yet.
